### ISSUE TITLE
master-linux64 PDF output all black squares

### ISSUE THREAD

**Issue by TomKaltz** [buke/GreenOdoo#1]
Ubuntu 14.04 LTS
English US

**Comment by buke** [comment]
hi ~ 

Could you give me more detail information ? And how to Reproduce it ?

Thanks

**Comment by TomKaltz** [comment]
Any and all reports from Odoo output black squares for all text.  I have
tried changing report default font to no avail.

Steps to reproduce.
1. Install fresh Ubuntu Server 14.04 LTS
2. git clone GreenOdoo branch master-linux64 (I have tried to 7.0-linux64
branch, same symptom)
3. start.sh
4. create database
5. install invoicing, sales, purchasing, accounting, etc
6. print any financial report, invoice, purchase order, etc.

**Comment by buke** [comment]
What's your report language? Can you should check the report with english ?

**Comment by TomKaltz** [comment]
That is the language I tested.

On Sunday, June 15, 2014, buke notifications@github.com wrote:

> What's your report language? Can you should check the report with english ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/buke/GreenOdoo/issues/1#issuecomment-46116724.

## 

Thomas R. Kaltz III

(586) 214-7150 cell
(866) 855-6350 fax

**Comment by buke** [comment]
Can not reproduce . Please check your env.

![20140616191103](https://cloud.githubusercontent.com/assets/1013738/3286368/c699edf8-f547-11e3-9044-48b3de091dc0.png)
