### ISSUE TITLE
阿里云主机 windows 服务器 安装 greenodoo win32报 msvcr100.dll

### ISSUE THREAD

**Issue by dw250100785** [buke/GreenOdoo#4]
按照报错提示，我百度msvcr100.dll，http://www.pc6.com/softview/SoftView_53688.html

将msvcr100.dll 放到 c:/windows/system,32下，ok了

**Comment by buke** [comment]
绿色版带了 msvcr100.dll 在 D:\GreenOdoo-8.0-win32\runtime\python\Lib\site-packages\psycopg2 下

我不知道那个模块还依赖 msvcr100.dll  ，你有空能否试试，不要放在 system 下

试试放在别的位置能否解决你的问题？ 如 python 的文件夹.

如能解决请回复。

**Comment by buke** [comment]
经过 @dw250100785  测试，添加到 runtime\pgsql\bin 下即可

https://github.com/buke/GreenOdoo-Runtime/commit/5c3406100673aab94a4ab7a2691cf232a3c93e17
