### ISSUE TITLE
pip 和 pip-2.7 指定的 python不正确

### ISSUE THREAD

**Issue by ccdos** [buke/GreenOdoo#7]
# !/usr/bin/env /home/buke/openerp-7.0-12/python/bin/python

没有指向绿色版的 python

**Comment by buke** [comment]
收到，择日修正

**Comment by buke** [comment]
shebang 不能使用相对路径，请自行更改。或使用：

$ ./runtime/python/bin/python ./runtime/python/bin/pip install xxx 

运行
